/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaoCaoRouteImport } from './routes/bao-cao'
import { Route as ChamCongRouteImport } from './routes/cham-cong'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as DeNghiRouteImport } from './routes/de-nghi'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GhiChuRouteImport } from './routes/ghi-chu'
import { Route as HoSoRouteImport } from './routes/ho-so'
import { Route as HuongDanRouteImport } from './routes/huong-dan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NhanSuRouteImport } from './routes/nhan-su'
import { Route as NhiemVuRouteImport } from './routes/nhiem-vu'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as TrungTamRouteImport } from './routes/trung-tam'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as BaoCaoBangChamCongRouteImport } from './routes/bao-cao/bang-cham-cong'
import { Route as BaoCaoBangCheckInRouteImport } from './routes/bao-cao/bang-check-in'
import { Route as BaoCaoBangNhiemVuRouteImport } from './routes/bao-cao/bang-nhiem-vu'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoCaoRoute = BaoCaoRouteImport.update({
  id: '/bao-cao',
  path: '/bao-cao',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamCongRoute = ChamCongRouteImport.update({
  id: '/cham-cong',
  path: '/cham-cong',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DeNghiRoute = DeNghiRouteImport.update({
  id: '/de-nghi',
  path: '/de-nghi',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GhiChuRoute = GhiChuRouteImport.update({
  id: '/ghi-chu',
  path: '/ghi-chu',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoRoute = HoSoRouteImport.update({
  id: '/ho-so',
  path: '/ho-so',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanRoute = HuongDanRouteImport.update({
  id: '/huong-dan',
  path: '/huong-dan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NhanSuRoute = NhanSuRouteImport.update({
  id: '/nhan-su',
  path: '/nhan-su',
  getParentRoute: () => rootRouteImport,
} as any)
const NhiemVuRoute = NhiemVuRouteImport.update({
  id: '/nhiem-vu',
  path: '/nhiem-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const TrungTamRoute = TrungTamRouteImport.update({
  id: '/trung-tam',
  path: '/trung-tam',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoCaoBangChamCongRoute = BaoCaoBangChamCongRouteImport.update({
  id: '/bang-cham-cong',
  path: '/bang-cham-cong',
  getParentRoute: () => BaoCaoRoute,
} as any)
const BaoCaoBangCheckInRoute = BaoCaoBangCheckInRouteImport.update({
  id: '/bang-check-in',
  path: '/bang-check-in',
  getParentRoute: () => BaoCaoRoute,
} as any)
const BaoCaoBangNhiemVuRoute = BaoCaoBangNhiemVuRouteImport.update({
  id: '/bang-nhiem-vu',
  path: '/bang-nhiem-vu',
  getParentRoute: () => BaoCaoRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRouteWithChildren
  '/cham-cong': typeof ChamCongRoute
  '/change-password': typeof ChangePasswordRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/de-nghi': typeof DeNghiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ghi-chu': typeof GhiChuRoute
  '/ho-so': typeof HoSoRoute
  '/huong-dan': typeof HuongDanRoute
  '/login': typeof LoginRoute
  '/nhan-su': typeof NhanSuRoute
  '/nhiem-vu': typeof NhiemVuRoute
  '/preview': typeof PreviewRoute
  '/trung-tam': typeof TrungTamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/bao-cao/bang-cham-cong': typeof BaoCaoBangChamCongRoute
  '/bao-cao/bang-check-in': typeof BaoCaoBangCheckInRoute
  '/bao-cao/bang-nhiem-vu': typeof BaoCaoBangNhiemVuRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRouteWithChildren
  '/cham-cong': typeof ChamCongRoute
  '/change-password': typeof ChangePasswordRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/de-nghi': typeof DeNghiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ghi-chu': typeof GhiChuRoute
  '/ho-so': typeof HoSoRoute
  '/huong-dan': typeof HuongDanRoute
  '/login': typeof LoginRoute
  '/nhan-su': typeof NhanSuRoute
  '/nhiem-vu': typeof NhiemVuRoute
  '/preview': typeof PreviewRoute
  '/trung-tam': typeof TrungTamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/bao-cao/bang-cham-cong': typeof BaoCaoBangChamCongRoute
  '/bao-cao/bang-check-in': typeof BaoCaoBangCheckInRoute
  '/bao-cao/bang-nhiem-vu': typeof BaoCaoBangNhiemVuRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRouteWithChildren
  '/cham-cong': typeof ChamCongRoute
  '/change-password': typeof ChangePasswordRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/de-nghi': typeof DeNghiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ghi-chu': typeof GhiChuRoute
  '/ho-so': typeof HoSoRoute
  '/huong-dan': typeof HuongDanRoute
  '/login': typeof LoginRoute
  '/nhan-su': typeof NhanSuRoute
  '/nhiem-vu': typeof NhiemVuRoute
  '/preview': typeof PreviewRoute
  '/trung-tam': typeof TrungTamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/bao-cao/bang-cham-cong': typeof BaoCaoBangChamCongRoute
  '/bao-cao/bang-check-in': typeof BaoCaoBangCheckInRoute
  '/bao-cao/bang-nhiem-vu': typeof BaoCaoBangNhiemVuRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bao-cao'
    | '/cham-cong'
    | '/change-password'
    | '/chat'
    | '/check-in'
    | '/de-nghi'
    | '/forgot-password'
    | '/ghi-chu'
    | '/ho-so'
    | '/huong-dan'
    | '/login'
    | '/nhan-su'
    | '/nhiem-vu'
    | '/preview'
    | '/trung-tam'
    | '/admin/approvals'
    | '/admin/permissions'
    | '/bao-cao/bang-cham-cong'
    | '/bao-cao/bang-check-in'
    | '/bao-cao/bang-nhiem-vu'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bao-cao'
    | '/cham-cong'
    | '/change-password'
    | '/chat'
    | '/check-in'
    | '/de-nghi'
    | '/forgot-password'
    | '/ghi-chu'
    | '/ho-so'
    | '/huong-dan'
    | '/login'
    | '/nhan-su'
    | '/nhiem-vu'
    | '/preview'
    | '/trung-tam'
    | '/admin/approvals'
    | '/admin/permissions'
    | '/bao-cao/bang-cham-cong'
    | '/bao-cao/bang-check-in'
    | '/bao-cao/bang-nhiem-vu'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bao-cao'
    | '/cham-cong'
    | '/change-password'
    | '/chat'
    | '/check-in'
    | '/de-nghi'
    | '/forgot-password'
    | '/ghi-chu'
    | '/ho-so'
    | '/huong-dan'
    | '/login'
    | '/nhan-su'
    | '/nhiem-vu'
    | '/preview'
    | '/trung-tam'
    | '/admin/approvals'
    | '/admin/permissions'
    | '/bao-cao/bang-cham-cong'
    | '/bao-cao/bang-check-in'
    | '/bao-cao/bang-nhiem-vu'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoCaoRoute: typeof BaoCaoRouteWithChildren
  ChamCongRoute: typeof ChamCongRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ChatRoute: typeof ChatRoute
  CheckInRoute: typeof CheckInRoute
  DeNghiRoute: typeof DeNghiRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GhiChuRoute: typeof GhiChuRoute
  HoSoRoute: typeof HoSoRoute
  HuongDanRoute: typeof HuongDanRoute
  LoginRoute: typeof LoginRoute
  NhanSuRoute: typeof NhanSuRoute
  NhiemVuRoute: typeof NhiemVuRoute
  PreviewRoute: typeof PreviewRoute
  TrungTamRoute: typeof TrungTamRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-cao': {
      id: '/bao-cao'
      path: '/bao-cao'
      fullPath: '/bao-cao'
      preLoaderRoute: typeof BaoCaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cham-cong': {
      id: '/cham-cong'
      path: '/cham-cong'
      fullPath: '/cham-cong'
      preLoaderRoute: typeof ChamCongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de-nghi': {
      id: '/de-nghi'
      path: '/de-nghi'
      fullPath: '/de-nghi'
      preLoaderRoute: typeof DeNghiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghi-chu': {
      id: '/ghi-chu'
      path: '/ghi-chu'
      fullPath: '/ghi-chu'
      preLoaderRoute: typeof GhiChuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so': {
      id: '/ho-so'
      path: '/ho-so'
      fullPath: '/ho-so'
      preLoaderRoute: typeof HoSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan': {
      id: '/huong-dan'
      path: '/huong-dan'
      fullPath: '/huong-dan'
      preLoaderRoute: typeof HuongDanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhan-su': {
      id: '/nhan-su'
      path: '/nhan-su'
      fullPath: '/nhan-su'
      preLoaderRoute: typeof NhanSuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhiem-vu': {
      id: '/nhiem-vu'
      path: '/nhiem-vu'
      fullPath: '/nhiem-vu'
      preLoaderRoute: typeof NhiemVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trung-tam': {
      id: '/trung-tam'
      path: '/trung-tam'
      fullPath: '/trung-tam'
      preLoaderRoute: typeof TrungTamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-cao/bang-cham-cong': {
      id: '/bao-cao/bang-cham-cong'
      path: '/bang-cham-cong'
      fullPath: '/bao-cao/bang-cham-cong'
      preLoaderRoute: typeof BaoCaoBangChamCongRouteImport
      parentRoute: typeof BaoCaoRoute
    }
    '/bao-cao/bang-check-in': {
      id: '/bao-cao/bang-check-in'
      path: '/bang-check-in'
      fullPath: '/bao-cao/bang-check-in'
      preLoaderRoute: typeof BaoCaoBangCheckInRouteImport
      parentRoute: typeof BaoCaoRoute
    }
    '/bao-cao/bang-nhiem-vu': {
      id: '/bao-cao/bang-nhiem-vu'
      path: '/bang-nhiem-vu'
      fullPath: '/bao-cao/bang-nhiem-vu'
      preLoaderRoute: typeof BaoCaoBangNhiemVuRouteImport
      parentRoute: typeof BaoCaoRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BaoCaoRouteChildren {
  BaoCaoBangChamCongRoute: typeof BaoCaoBangChamCongRoute
  BaoCaoBangCheckInRoute: typeof BaoCaoBangCheckInRoute
  BaoCaoBangNhiemVuRoute: typeof BaoCaoBangNhiemVuRoute
}

const BaoCaoRouteChildren: BaoCaoRouteChildren = {
  BaoCaoBangChamCongRoute: BaoCaoBangChamCongRoute,
  BaoCaoBangCheckInRoute: BaoCaoBangCheckInRoute,
  BaoCaoBangNhiemVuRoute: BaoCaoBangNhiemVuRoute,
}

const BaoCaoRouteWithChildren =
  BaoCaoRoute._addFileChildren(BaoCaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoCaoRoute: BaoCaoRouteWithChildren,
  ChamCongRoute: ChamCongRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ChatRoute: ChatRoute,
  CheckInRoute: CheckInRoute,
  DeNghiRoute: DeNghiRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GhiChuRoute: GhiChuRoute,
  HoSoRoute: HoSoRoute,
  HuongDanRoute: HuongDanRoute,
  LoginRoute: LoginRoute,
  NhanSuRoute: NhanSuRoute,
  NhiemVuRoute: NhiemVuRoute,
  PreviewRoute: PreviewRoute,
  TrungTamRoute: TrungTamRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
